[{"TimeUTC":"2025-04-05 21:47:28","timestampInMs":1743889648542,"requestPath":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app/favicon.png","requestMethod":"GET","requestQueryString":"","responseStatusCode":-1,"requestId":"rqw7z-1743889648281-650fc133fb3a","requestUserAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main","host":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app","deploymentDomain":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app","deploymentId":"dpl_4pcG9m4brqP9rb2AwdT71TaYXvJo","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap_external>\", line 1132, in get_code\nFile \"<frozen importlib._bootstrap_external>\", line 1190, in get_data\nFileNotFoundError: [Errno 2] No such file or directory: '/var/task/main.py'\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_fQbLhzmWC1VlriP6bSnlnrIgN4Mc"},{"TimeUTC":"2025-04-05 21:47:28","timestampInMs":1743889648323,"requestPath":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app/favicon.png","requestMethod":"GET","requestQueryString":"","responseStatusCode":500,"requestId":"rqw7z-1743889648281-650fc133fb3a","requestUserAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main","host":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app","deploymentDomain":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app","deploymentId":"dpl_4pcG9m4brqP9rb2AwdT71TaYXvJo","durationMs":181,"region":"iad1","maxMemoryUsed":16,"memorySize":1024,"message":"","projectId":"prj_fQbLhzmWC1VlriP6bSnlnrIgN4Mc"},{"TimeUTC":"2025-04-05 21:47:27","timestampInMs":1743889647204,"requestPath":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app/favicon.png","requestMethod":"GET","requestQueryString":"","responseStatusCode":-1,"requestId":"tt7dh-1743889646976-df9bf7f66a35","requestUserAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main","host":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app","deploymentDomain":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app","deploymentId":"dpl_4pcG9m4brqP9rb2AwdT71TaYXvJo","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap_external>\", line 1132, in get_code\nFile \"<frozen importlib._bootstrap_external>\", line 1190, in get_data\nFileNotFoundError: [Errno 2] No such file or directory: '/var/task/main.py'\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_fQbLhzmWC1VlriP6bSnlnrIgN4Mc"},{"TimeUTC":"2025-04-05 21:47:27","timestampInMs":1743889647018,"requestPath":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app/favicon.png","requestMethod":"GET","requestQueryString":"","responseStatusCode":500,"requestId":"tt7dh-1743889646976-df9bf7f66a35","requestUserAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main","host":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app","deploymentDomain":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app","deploymentId":"dpl_4pcG9m4brqP9rb2AwdT71TaYXvJo","durationMs":168,"region":"iad1","maxMemoryUsed":16,"memorySize":1024,"message":"","projectId":"prj_fQbLhzmWC1VlriP6bSnlnrIgN4Mc"},{"TimeUTC":"2025-04-05 21:47:26","timestampInMs":1743889646925,"requestPath":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app/favicon.ico","requestMethod":"GET","requestQueryString":"","responseStatusCode":-1,"requestId":"xrq6k-1743889646668-82f6e793d9bd","requestUserAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main","host":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app","deploymentDomain":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app","deploymentId":"dpl_4pcG9m4brqP9rb2AwdT71TaYXvJo","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap_external>\", line 1132, in get_code\nFile \"<frozen importlib._bootstrap_external>\", line 1190, in get_data\nFileNotFoundError: [Errno 2] No such file or directory: '/var/task/main.py'\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_fQbLhzmWC1VlriP6bSnlnrIgN4Mc"},{"TimeUTC":"2025-04-05 21:47:26","timestampInMs":1743889646741,"requestPath":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app/favicon.ico","requestMethod":"GET","requestQueryString":"","responseStatusCode":500,"requestId":"xrq6k-1743889646668-82f6e793d9bd","requestUserAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main","host":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app","deploymentDomain":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app","deploymentId":"dpl_4pcG9m4brqP9rb2AwdT71TaYXvJo","durationMs":169,"region":"iad1","maxMemoryUsed":16,"memorySize":1024,"message":"","projectId":"prj_fQbLhzmWC1VlriP6bSnlnrIgN4Mc"},{"TimeUTC":"2025-04-05 21:47:24","timestampInMs":1743889644542,"requestPath":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app/favicon.ico","requestMethod":"GET","requestQueryString":"","responseStatusCode":-1,"requestId":"sbnmt-1743889644298-19ef0d27d81e","requestUserAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main","host":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app","deploymentDomain":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app","deploymentId":"dpl_4pcG9m4brqP9rb2AwdT71TaYXvJo","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap_external>\", line 1132, in get_code\nFile \"<frozen importlib._bootstrap_external>\", line 1190, in get_data\nFileNotFoundError: [Errno 2] No such file or directory: '/var/task/main.py'\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_fQbLhzmWC1VlriP6bSnlnrIgN4Mc"},{"TimeUTC":"2025-04-05 21:47:24","timestampInMs":1743889644340,"requestPath":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app/favicon.ico","requestMethod":"GET","requestQueryString":"","responseStatusCode":500,"requestId":"sbnmt-1743889644298-19ef0d27d81e","requestUserAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main","host":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app","deploymentDomain":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app","deploymentId":"dpl_4pcG9m4brqP9rb2AwdT71TaYXvJo","durationMs":182,"region":"iad1","maxMemoryUsed":16,"memorySize":1024,"message":"","projectId":"prj_fQbLhzmWC1VlriP6bSnlnrIgN4Mc"},{"TimeUTC":"2025-04-05 21:47:23","timestampInMs":1743889643243,"requestPath":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app/favicon.ico","requestMethod":"GET","requestQueryString":"","responseStatusCode":-1,"requestId":"9rwhc-1743889643011-cf8e0e6bee5e","requestUserAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main","host":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app","deploymentDomain":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app","deploymentId":"dpl_4pcG9m4brqP9rb2AwdT71TaYXvJo","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap_external>\", line 1132, in get_code\nFile \"<frozen importlib._bootstrap_external>\", line 1190, in get_data\nFileNotFoundError: [Errno 2] No such file or directory: '/var/task/main.py'\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_fQbLhzmWC1VlriP6bSnlnrIgN4Mc"},{"TimeUTC":"2025-04-05 21:47:23","timestampInMs":1743889643053,"requestPath":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app/favicon.ico","requestMethod":"GET","requestQueryString":"","responseStatusCode":500,"requestId":"9rwhc-1743889643011-cf8e0e6bee5e","requestUserAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main","host":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app","deploymentDomain":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app","deploymentId":"dpl_4pcG9m4brqP9rb2AwdT71TaYXvJo","durationMs":169,"region":"iad1","maxMemoryUsed":15,"memorySize":1024,"message":"","projectId":"prj_fQbLhzmWC1VlriP6bSnlnrIgN4Mc"},{"TimeUTC":"2025-04-05 21:47:22","timestampInMs":1743889642882,"requestPath":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app/","requestMethod":"GET","requestQueryString":"","responseStatusCode":-1,"requestId":"kvnj8-1743889642647-cbd1751344bf","requestUserAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main","host":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app","deploymentDomain":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app","deploymentId":"dpl_4pcG9m4brqP9rb2AwdT71TaYXvJo","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap_external>\", line 1132, in get_code\nFile \"<frozen importlib._bootstrap_external>\", line 1190, in get_data\nFileNotFoundError: [Errno 2] No such file or directory: '/var/task/main.py'\nPython process exited with exit status: 1. The logs above can help with debugging the issue.\nTraceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap_external>\", line 1132, in get_code\nFile \"<frozen importlib._bootstrap_external>\", line 1190, in get_data\nFileNotFoundError: [Errno 2] No such file or directory: '/var/task/main.py'\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_fQbLhzmWC1VlriP6bSnlnrIgN4Mc"},{"TimeUTC":"2025-04-05 21:47:22","timestampInMs":1743889642695,"requestPath":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app/","requestMethod":"GET","requestQueryString":"","responseStatusCode":500,"requestId":"kvnj8-1743889642647-cbd1751344bf","requestUserAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main","host":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app","deploymentDomain":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app","deploymentId":"dpl_4pcG9m4brqP9rb2AwdT71TaYXvJo","durationMs":171,"region":"iad1","maxMemoryUsed":15,"memorySize":1024,"message":"","projectId":"prj_fQbLhzmWC1VlriP6bSnlnrIgN4Mc"},{"TimeUTC":"2025-04-05 21:47:21","timestampInMs":1743889641563,"requestPath":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app/","requestMethod":"GET","requestQueryString":"","responseStatusCode":-1,"requestId":"4q2vh-1743889641326-b13a5a85ad39","requestUserAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main","host":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app","deploymentDomain":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app","deploymentId":"dpl_4pcG9m4brqP9rb2AwdT71TaYXvJo","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap_external>\", line 1132, in get_code\nFile \"<frozen importlib._bootstrap_external>\", line 1190, in get_data\nFileNotFoundError: [Errno 2] No such file or directory: '/var/task/main.py'\nPython process exited with exit status: 1. The logs above can help with debugging the issue.\nTraceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap_external>\", line 1132, in get_code\nFile \"<frozen importlib._bootstrap_external>\", line 1190, in get_data\nFileNotFoundError: [Errno 2] No such file or directory: '/var/task/main.py'\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_fQbLhzmWC1VlriP6bSnlnrIgN4Mc"},{"TimeUTC":"2025-04-05 21:47:21","timestampInMs":1743889641374,"requestPath":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app/","requestMethod":"GET","requestQueryString":"","responseStatusCode":500,"requestId":"4q2vh-1743889641326-b13a5a85ad39","requestUserAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main","host":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app","deploymentDomain":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app","deploymentId":"dpl_4pcG9m4brqP9rb2AwdT71TaYXvJo","durationMs":168,"region":"iad1","maxMemoryUsed":16,"memorySize":1024,"message":"","projectId":"prj_fQbLhzmWC1VlriP6bSnlnrIgN4Mc"},{"TimeUTC":"2025-04-05 21:45:19","timestampInMs":1743889519466,"requestPath":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app/favicon.ico","requestMethod":"GET","requestQueryString":"","responseStatusCode":-1,"requestId":"s62lz-1743889519225-389985e566d8","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main","host":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app","deploymentDomain":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app","deploymentId":"dpl_4pcG9m4brqP9rb2AwdT71TaYXvJo","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap_external>\", line 1132, in get_code\nFile \"<frozen importlib._bootstrap_external>\", line 1190, in get_data\nFileNotFoundError: [Errno 2] No such file or directory: '/var/task/main.py'\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_fQbLhzmWC1VlriP6bSnlnrIgN4Mc"},{"TimeUTC":"2025-04-05 21:45:19","timestampInMs":1743889519266,"requestPath":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app/favicon.ico","requestMethod":"GET","requestQueryString":"","responseStatusCode":500,"requestId":"s62lz-1743889519225-389985e566d8","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main","host":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app","deploymentDomain":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app","deploymentId":"dpl_4pcG9m4brqP9rb2AwdT71TaYXvJo","durationMs":179,"region":"iad1","maxMemoryUsed":15,"memorySize":1024,"message":"","projectId":"prj_fQbLhzmWC1VlriP6bSnlnrIgN4Mc"},{"TimeUTC":"2025-04-05 21:45:19","timestampInMs":1743889519180,"requestPath":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app/favicon.ico","requestMethod":"GET","requestQueryString":"","responseStatusCode":-1,"requestId":"pk76x-1743889518921-095a6d0c1eb6","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main","host":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app","deploymentDomain":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app","deploymentId":"dpl_4pcG9m4brqP9rb2AwdT71TaYXvJo","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap_external>\", line 1132, in get_code\nFile \"<frozen importlib._bootstrap_external>\", line 1190, in get_data\nFileNotFoundError: [Errno 2] No such file or directory: '/var/task/main.py'\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_fQbLhzmWC1VlriP6bSnlnrIgN4Mc"},{"TimeUTC":"2025-04-05 21:45:19","timestampInMs":1743889519157,"requestPath":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app/","requestMethod":"GET","requestQueryString":"","responseStatusCode":-1,"requestId":"8hc8j-1743889518902-4f10c05c4e9a","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main","host":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app","deploymentDomain":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app","deploymentId":"dpl_4pcG9m4brqP9rb2AwdT71TaYXvJo","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap_external>\", line 1132, in get_code\nFile \"<frozen importlib._bootstrap_external>\", line 1190, in get_data\nFileNotFoundError: [Errno 2] No such file or directory: '/var/task/main.py'\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_fQbLhzmWC1VlriP6bSnlnrIgN4Mc"},{"TimeUTC":"2025-04-05 21:45:18","timestampInMs":1743889518967,"requestPath":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app/favicon.ico","requestMethod":"GET","requestQueryString":"","responseStatusCode":500,"requestId":"pk76x-1743889518921-095a6d0c1eb6","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main","host":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app","deploymentDomain":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app","deploymentId":"dpl_4pcG9m4brqP9rb2AwdT71TaYXvJo","durationMs":194,"region":"iad1","maxMemoryUsed":16,"memorySize":1024,"message":"","projectId":"prj_fQbLhzmWC1VlriP6bSnlnrIgN4Mc"},{"TimeUTC":"2025-04-05 21:45:18","timestampInMs":1743889518943,"requestPath":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app/","requestMethod":"GET","requestQueryString":"","responseStatusCode":500,"requestId":"8hc8j-1743889518902-4f10c05c4e9a","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main","host":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app","deploymentDomain":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app","deploymentId":"dpl_4pcG9m4brqP9rb2AwdT71TaYXvJo","durationMs":194,"region":"iad1","maxMemoryUsed":43,"memorySize":1024,"message":"","projectId":"prj_fQbLhzmWC1VlriP6bSnlnrIgN4Mc"},{"TimeUTC":"2025-04-05 21:45:18","timestampInMs":1743889518841,"requestPath":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app/","requestMethod":"GET","requestQueryString":"","responseStatusCode":-1,"requestId":"qgvwq-1743889518589-5f29f0e72f5d","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main","host":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app","deploymentDomain":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app","deploymentId":"dpl_4pcG9m4brqP9rb2AwdT71TaYXvJo","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap_external>\", line 1132, in get_code\nFile \"<frozen importlib._bootstrap_external>\", line 1190, in get_data\nFileNotFoundError: [Errno 2] No such file or directory: '/var/task/main.py'\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_fQbLhzmWC1VlriP6bSnlnrIgN4Mc"},{"TimeUTC":"2025-04-05 21:45:18","timestampInMs":1743889518781,"requestPath":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app/","requestMethod":"GET","requestQueryString":"","responseStatusCode":-1,"requestId":"br5qc-1743889518496-558c19549201","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main","host":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app","deploymentDomain":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app","deploymentId":"dpl_4pcG9m4brqP9rb2AwdT71TaYXvJo","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap_external>\", line 1132, in get_code\nFile \"<frozen importlib._bootstrap_external>\", line 1190, in get_data\nFileNotFoundError: [Errno 2] No such file or directory: '/var/task/main.py'\nPython process exited with exit status: 1. The logs above can help with debugging the issue.\nTraceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap_external>\", line 1132, in get_code\nFile \"<frozen importlib._bootstrap_external>\", line 1190, in get_data\nFileNotFoundError: [Errno 2] No such file or directory: '/var/task/main.py'\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_fQbLhzmWC1VlriP6bSnlnrIgN4Mc"},{"TimeUTC":"2025-04-05 21:45:18","timestampInMs":1743889518631,"requestPath":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app/","requestMethod":"GET","requestQueryString":"","responseStatusCode":500,"requestId":"qgvwq-1743889518589-5f29f0e72f5d","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main","host":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app","deploymentDomain":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app","deploymentId":"dpl_4pcG9m4brqP9rb2AwdT71TaYXvJo","durationMs":194,"region":"iad1","maxMemoryUsed":43,"memorySize":1024,"message":"","projectId":"prj_fQbLhzmWC1VlriP6bSnlnrIgN4Mc"},{"TimeUTC":"2025-04-05 21:45:18","timestampInMs":1743889518539,"requestPath":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app/","requestMethod":"GET","requestQueryString":"","responseStatusCode":500,"requestId":"br5qc-1743889518496-558c19549201","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main","host":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app","deploymentDomain":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app","deploymentId":"dpl_4pcG9m4brqP9rb2AwdT71TaYXvJo","durationMs":185,"region":"iad1","maxMemoryUsed":16,"memorySize":1024,"message":"","projectId":"prj_fQbLhzmWC1VlriP6bSnlnrIgN4Mc"},{"TimeUTC":"2025-04-05 21:45:18","timestampInMs":1743889518467,"requestPath":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app/","requestMethod":"GET","requestQueryString":"","responseStatusCode":-1,"requestId":"gjcc7-1743889518236-abc5818b01af","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main","host":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app","deploymentDomain":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app","deploymentId":"dpl_4pcG9m4brqP9rb2AwdT71TaYXvJo","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap_external>\", line 1132, in get_code\nFile \"<frozen importlib._bootstrap_external>\", line 1190, in get_data\nFileNotFoundError: [Errno 2] No such file or directory: '/var/task/main.py'\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_fQbLhzmWC1VlriP6bSnlnrIgN4Mc"},{"TimeUTC":"2025-04-05 21:45:18","timestampInMs":1743889518278,"requestPath":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app/","requestMethod":"GET","requestQueryString":"","responseStatusCode":500,"requestId":"gjcc7-1743889518236-abc5818b01af","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main","host":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app","deploymentDomain":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app","deploymentId":"dpl_4pcG9m4brqP9rb2AwdT71TaYXvJo","durationMs":170,"region":"iad1","maxMemoryUsed":16,"memorySize":1024,"message":"","projectId":"prj_fQbLhzmWC1VlriP6bSnlnrIgN4Mc"},{"TimeUTC":"2025-04-05 21:45:16","timestampInMs":1743889516421,"requestPath":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app/","requestMethod":"GET","requestQueryString":"","responseStatusCode":-1,"requestId":"t945g-1743889515999-94f7b46b4fbe","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main","host":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app","deploymentDomain":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app","deploymentId":"dpl_4pcG9m4brqP9rb2AwdT71TaYXvJo","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap_external>\", line 1132, in get_code\nFile \"<frozen importlib._bootstrap_external>\", line 1190, in get_data\nFileNotFoundError: [Errno 2] No such file or directory: '/var/task/main.py'\nPython process exited with exit status: 1. The logs above can help with debugging the issue.\nTraceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap_external>\", line 1132, in get_code\nFile \"<frozen importlib._bootstrap_external>\", line 1190, in get_data\nFileNotFoundError: [Errno 2] No such file or directory: '/var/task/main.py'\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_fQbLhzmWC1VlriP6bSnlnrIgN4Mc"},{"TimeUTC":"2025-04-05 21:45:16","timestampInMs":1743889516153,"requestPath":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app/","requestMethod":"GET","requestQueryString":"","responseStatusCode":500,"requestId":"t945g-1743889515999-94f7b46b4fbe","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main","host":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app","deploymentDomain":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app","deploymentId":"dpl_4pcG9m4brqP9rb2AwdT71TaYXvJo","durationMs":172,"region":"iad1","maxMemoryUsed":16,"memorySize":1024,"message":"","projectId":"prj_fQbLhzmWC1VlriP6bSnlnrIgN4Mc"},{"TimeUTC":"2025-04-05 21:45:16","timestampInMs":1743889516121,"requestPath":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app/","requestMethod":"GET","requestQueryString":"","responseStatusCode":-1,"requestId":"zmfgk-1743889515748-3a8dccabf1a6","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main","host":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app","deploymentDomain":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app","deploymentId":"dpl_4pcG9m4brqP9rb2AwdT71TaYXvJo","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap_external>\", line 1132, in get_code\nFile \"<frozen importlib._bootstrap_external>\", line 1190, in get_data\nFileNotFoundError: [Errno 2] No such file or directory: '/var/task/main.py'\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_fQbLhzmWC1VlriP6bSnlnrIgN4Mc"},{"TimeUTC":"2025-04-05 21:45:15","timestampInMs":1743889515898,"requestPath":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app/","requestMethod":"GET","requestQueryString":"","responseStatusCode":500,"requestId":"zmfgk-1743889515748-3a8dccabf1a6","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main","host":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app","deploymentDomain":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app","deploymentId":"dpl_4pcG9m4brqP9rb2AwdT71TaYXvJo","durationMs":198,"region":"iad1","maxMemoryUsed":16,"memorySize":1024,"message":"","projectId":"prj_fQbLhzmWC1VlriP6bSnlnrIgN4Mc"},{"TimeUTC":"2025-04-05 21:45:14","timestampInMs":1743889514925,"requestPath":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app/","requestMethod":"GET","requestQueryString":"","responseStatusCode":-1,"requestId":"dmmgm-1743889513840-38ebbe19661f","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main","host":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app","deploymentDomain":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app","deploymentId":"dpl_4pcG9m4brqP9rb2AwdT71TaYXvJo","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap_external>\", line 1132, in get_code\nFile \"<frozen importlib._bootstrap_external>\", line 1190, in get_data\nFileNotFoundError: [Errno 2] No such file or directory: '/var/task/main.py'\nPython process exited with exit status: 1. The logs above can help with debugging the issue.\nTraceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap_external>\", line 1132, in get_code\nFile \"<frozen importlib._bootstrap_external>\", line 1190, in get_data\nFileNotFoundError: [Errno 2] No such file or directory: '/var/task/main.py'\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_fQbLhzmWC1VlriP6bSnlnrIgN4Mc"},{"TimeUTC":"2025-04-05 21:45:14","timestampInMs":1743889514638,"requestPath":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app/","requestMethod":"GET","requestQueryString":"","responseStatusCode":-1,"requestId":"xq2zz-1743889513883-ce7610d3bd73","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main","host":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app","deploymentDomain":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app","deploymentId":"dpl_4pcG9m4brqP9rb2AwdT71TaYXvJo","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap_external>\", line 1132, in get_code\nFile \"<frozen importlib._bootstrap_external>\", line 1190, in get_data\nFileNotFoundError: [Errno 2] No such file or directory: '/var/task/main.py'\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_fQbLhzmWC1VlriP6bSnlnrIgN4Mc"},{"TimeUTC":"2025-04-05 21:45:14","timestampInMs":1743889514421,"requestPath":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app/","requestMethod":"GET","requestQueryString":"","responseStatusCode":500,"requestId":"xq2zz-1743889513883-ce7610d3bd73","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main","host":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app","deploymentDomain":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app","deploymentId":"dpl_4pcG9m4brqP9rb2AwdT71TaYXvJo","durationMs":197,"region":"iad1","maxMemoryUsed":43,"memorySize":1024,"message":"","projectId":"prj_fQbLhzmWC1VlriP6bSnlnrIgN4Mc"},{"TimeUTC":"2025-04-05 21:45:14","timestampInMs":1743889514419,"requestPath":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app/","requestMethod":"GET","requestQueryString":"","responseStatusCode":500,"requestId":"dmmgm-1743889513840-38ebbe19661f","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main","host":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app","deploymentDomain":"burna-dapp-nofm-ovo6wvui4-burna-dapps-projects.vercel.app","deploymentId":"dpl_4pcG9m4brqP9rb2AwdT71TaYXvJo","durationMs":173,"region":"iad1","maxMemoryUsed":15,"memorySize":1024,"message":"","projectId":"prj_fQbLhzmWC1VlriP6bSnlnrIgN4Mc"}]